update backup script

diff --git a/bin/backup b/bin/backup
--- a/bin/backup
+++ b/bin/backup
@@ -1,31 +1,32 @@
 #!/bin/bash
 
-SOURCE="/home/maximbaz/Dropbox /home/maximbaz/private /home/maximbaz/.dotfiles /home/maximbaz/.go/src/go-private /home/maximbaz/.ssh"
+SOURCE=".dotfiles .ssh .gnupg cloud Seafile"
 BACKUP_PATH="/run/media/maximbaz/Transcend/maximbaz"
 BACKUP_DIR="$BACKUP_PATH/$(date +%Y-%m-%d)"
 
 if [ ! -d "$BACKUP_PATH" ]; then
-  echo "Backup device '$BACKUP_PATH' does not exist, aborting."
-  exit 1
+    echo "Backup device '$BACKUP_PATH' does not exist, aborting."
+    exit 1
 fi
 
 if [ -d "$BACKUP_DIR" ]; then
-  read -p "Backup directory '$BACKUP_DIR' already exists, merge? [y/n] " -n 1 -r
-  echo
-  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
-    echo "Aborted."
-    exit 1
-  fi
+    read -p "Backup directory '$BACKUP_DIR' already exists, merge? [y/n] " -n 1 -r
+    echo
+    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
+        echo "Aborted."
+        exit 1
+    fi
 fi
 
+cd "$HOME"
 echo -e "\nBackup STARTED\n\nSource(s):   $SOURCE\nDestination: $BACKUP_DIR\n"
 rsync -a --info=progress2 $SOURCE $BACKUP_DIR
 exitcode=$?
 
 if [ "$exitcode" -eq "0" ]; then
-  echo -e "\nBackup SUCCESSFUL"
+    echo -e "\nBackup SUCCESSFUL"
 else
-  echo -e "\nBackup FAILED"
+    echo -e "\nBackup FAILED"
 fi
 
 echo -e "\n-------------------------------------------------------------------"
