check-mail: prevent parallel runs

diff --git a/bin/check-mail b/bin/check-mail
--- a/bin/check-mail
+++ b/bin/check-mail
@@ -1,5 +1,10 @@
 #!/bin/sh
 
+if pgrep mbsync >/dev/null || pgrep notmuch >/dev/null; then
+    echo "Sync in progress, aborting."
+    exit 1
+fi
+
 mbsync -a
 notmuch new
 
